import { City } from './types';

export const US_CITIES: City[] = [
  { name: 'New York', state: 'NY', airports: ['JFK', 'LGA', 'EWR'] },
  { name: 'Los Angeles', state: 'CA', airports: ['LAX'] },
  { name: 'Chicago', state: 'IL', airports: ['ORD', 'MDW'] },
  { name: 'Houston', state: 'TX', airports: ['IAH', 'HOU'] },
  { name: 'Phoenix', state: 'AZ', airports: ['PHX'] },
  { name: 'Philadelphia', state: 'PA', airports: ['PHL'] },
  { name: 'San Antonio', state: 'TX', airports: ['SAT'] },
  { name: 'San Diego', state: 'CA', airports: ['SAN'] },
  { name: 'Dallas', state: 'TX', airports: ['DFW', 'DAL'] },
  { name: 'Austin', state: 'TX', airports: ['AUS'] },
  { name: 'Jacksonville', state: 'FL', airports: ['JAX'] },
  { name: 'Fort Worth', state: 'TX', airports: ['DFW'] },
  { name: 'San Jose', state: 'CA', airports: ['SJC'] },
  { name: 'Columbus', state: 'OH', airports: ['CMH'] },
  { name: 'Charlotte', state: 'NC', airports: ['CLT'] },
  { name: 'Indianapolis', state: 'IN', airports: ['IND'] },
  { name: 'San Francisco', state: 'CA', airports: ['SFO'] },
  { name: 'Seattle', state: 'WA', airports: ['SEA'] },
  { name: 'Denver', state: 'CO', airports: ['DEN'] },
  { name: 'Washington', state: 'DC', airports: ['DCA', 'IAD'] },
  { name: 'Nashville', state: 'TN', airports: ['BNA'] },
  { name: 'Oklahoma City', state: 'OK', airports: ['OKC'] },
  { name: 'El Paso', state: 'TX', airports: ['ELP'] },
  { name: 'Boston', state: 'MA', airports: ['BOS'] },
  { name: 'Portland', state: 'OR', airports: ['PDX'] },
  { name: 'Las Vegas', state: 'NV', airports: ['LAS'] },
  { name: 'Memphis', state: 'TN', airports: ['MEM'] },
  { name: 'Louisville', state: 'KY', airports: ['SDF'] },
  { name: 'Baltimore', state: 'MD', airports: ['BWI'] },
  { name: 'Milwaukee', state: 'WI', airports: ['MKE'] },
  { name: 'Albuquerque', state: 'NM', airports: ['ABQ'] },
  { name: 'Tucson', state: 'AZ', airports: ['TUS'] },
  { name: 'Fresno', state: 'CA', airports: ['FAT'] },
  { name: 'Sacramento', state: 'CA', airports: ['SMF'] },
  { name: 'Mesa', state: 'AZ', airports: ['PHX'] },
  { name: 'Kansas City', state: 'MO', airports: ['MCI'] },
  { name: 'Atlanta', state: 'GA', airports: ['ATL'] },
  { name: 'Omaha', state: 'NE', airports: ['OMA'] },
  { name: 'Colorado Springs', state: 'CO', airports: ['COS'] },
  { name: 'Raleigh', state: 'NC', airports: ['RDU'] },
  { name: 'Long Beach', state: 'CA', airports: ['LGB'] },
  { name: 'Virginia Beach', state: 'VA', airports: ['ORF'] },
  { name: 'Miami', state: 'FL', airports: ['MIA'] },
  { name: 'Oakland', state: 'CA', airports: ['OAK'] },
  { name: 'Minneapolis', state: 'MN', airports: ['MSP'] },
  { name: 'Tampa', state: 'FL', airports: ['TPA'] },
  { name: 'New Orleans', state: 'LA', airports: ['MSY'] },
  { name: 'Cleveland', state: 'OH', airports: ['CLE'] },
  { name: 'Orlando', state: 'FL', airports: ['MCO'] },
  { name: 'Pittsburgh', state: 'PA', airports: ['PIT'] },
  // 51-100
  { name: 'St. Louis', state: 'MO', airports: ['STL'] },
  { name: 'Cincinnati', state: 'OH', airports: ['CVG'] },
  { name: 'Honolulu', state: 'HI', airports: ['HNL'] },
  { name: 'Anchorage', state: 'AK', airports: ['ANC'] },
  { name: 'Newark', state: 'NJ', airports: ['EWR'] },
  { name: 'Lexington', state: 'KY', airports: ['LEX'] },
  { name: 'Stockton', state: 'CA', airports: ['SCK'] },
  { name: 'Buffalo', state: 'NY', airports: ['BUF'] },
  { name: 'Corpus Christi', state: 'TX', airports: ['CRP'] },
  { name: 'St. Paul', state: 'MN', airports: ['MSP'] },
  { name: 'Santa Ana', state: 'CA', airports: ['SNA'] },
  { name: 'Henderson', state: 'NV', airports: ['LAS'] },
  { name: 'Greensboro', state: 'NC', airports: ['GSO'] },
  { name: 'Plano', state: 'TX', airports: ['DFW'] },
  { name: 'Lincoln', state: 'NE', airports: ['LNK'] },
  { name: 'Irvine', state: 'CA', airports: ['SNA'] },
  { name: 'Norfolk', state: 'VA', airports: ['ORF'] },
  { name: 'Rochester', state: 'NY', airports: ['ROC'] },
  { name: 'Chandler', state: 'AZ', airports: ['PHX'] },
  { name: 'Gilbert', state: 'AZ', airports: ['PHX'] },
  { name: 'Boise', state: 'ID', airports: ['BOI'] },
  { name: 'Spokane', state: 'WA', airports: ['GEG'] },
  { name: 'Richmond', state: 'VA', airports: ['RIC'] },
  { name: 'Des Moines', state: 'IA', airports: ['DSM'] },
  { name: 'Montgomery', state: 'AL', airports: ['MGM'] },
  { name: 'Birmingham', state: 'AL', airports: ['BHM'] },
  { name: 'Salt Lake City', state: 'UT', airports: ['SLC'] },
  { name: 'Baton Rouge', state: 'LA', airports: ['BTR'] },
  { name: 'Scottsdale', state: 'AZ', airports: ['PHX'] },
  { name: 'Reno', state: 'NV', airports: ['RNO'] },
  { name: 'Madison', state: 'WI', airports: ['MSN'] },
  { name: 'Glendale', state: 'AZ', airports: ['PHX'] },
  { name: 'Detroit', state: 'MI', airports: ['DTW'] },
  { name: 'Lubbock', state: 'TX', airports: ['LBB'] },
  { name: 'Laredo', state: 'TX', airports: ['LRD'] },
  { name: 'Durham', state: 'NC', airports: ['RDU'] },
  { name: 'Chesapeake', state: 'VA', airports: ['ORF'] },
  { name: 'Winston-Salem', state: 'NC', airports: ['GSO'] },
  { name: 'Garland', state: 'TX', airports: ['DFW'] },
  { name: 'North Las Vegas', state: 'NV', airports: ['LAS'] },
  { name: 'Hialeah', state: 'FL', airports: ['MIA'] },
  { name: 'Irving', state: 'TX', airports: ['DFW'] },
  { name: 'Fremont', state: 'CA', airports: ['SJC'] },
  { name: 'Providence', state: 'RI', airports: ['PVD'] },
  { name: 'Savannah', state: 'GA', airports: ['SAV'] },
  { name: 'Charleston', state: 'SC', airports: ['CHS'] },
  { name: 'Knoxville', state: 'TN', airports: ['TYS'] },
  { name: 'Little Rock', state: 'AR', airports: ['LIT'] },
  { name: 'Hartford', state: 'CT', airports: ['BDL'] },
  { name: 'Jackson', state: 'MS', airports: ['JAN'] },
];
